# Generated by Django 4.1 on 2022-09-09 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food_labeler", "0002_rename_total_count_question_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionuser",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="qu_food_labeler", to="food_labeler.question"
            ),
        ),
    ]
