# Generated by Django 4.1 on 2022-09-10 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food_labeler", "0003_alter_questionuser_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qu_food_labeler",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
