# Generated by Django 4.1 on 2022-09-11 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image_link1", models.CharField(max_length=800)),
                ("image_link2", models.CharField(max_length=800)),
                ("question_text", models.CharField(max_length=100)),
                ("photo1_count", models.IntegerField(default=0)),
                ("photo2_count", models.IntegerField(default=0)),
                ("similar_count", models.IntegerField(default=0)),
                ("count", models.IntegerField(default=0)),
                (
                    "final_answer",
                    models.IntegerField(
                        choices=[(0, "Photo1"), (1, "Photo2"), (2, "Similar"), (-1, "Not Defined")], default=-1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answer", models.IntegerField()),
                (
                    "question",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="food_compare.question"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qu_food_compare",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
