# Generated by Django 4.1 on 2022-09-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_caption", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="no_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="yes_count",
            field=models.IntegerField(default=0),
        ),
    ]
