# Generated by Django 4.1 on 2022-09-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_caption", "0002_alter_question_count_alter_question_no_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="not_sure_count",
            field=models.IntegerField(default=0),
        ),
    ]
