# Generated by Django 4.1 on 2022-09-09 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("image_caption", "0004_alter_question_cert_text_alter_question_image_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question_user",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qu_image_caption",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
