# Generated by Django 4.1 on 2022-09-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_labeler", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="total_count",
            new_name="count",
        ),
    ]
