# Generated by Django 4.1 on 2022-09-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentiment", "0002_alter_questionuser_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="not_sure_count",
        ),
        migrations.AddField(
            model_name="question",
            name="neutral_count",
            field=models.IntegerField(default=0),
        ),
    ]
